### ISSUE TITLE
Run single scenario outline example configuration doesn't work as expected

### ISSUE THREAD

**Issue by iromeo** [maximehamm/tzatziki#11]
At the moment Cucumber+ 9.0.2 suggests running a single example only if I click on the non-whitespace text in the corresponding line of examples table. 
![image](https://user-images.githubusercontent.com/72933/129972696-b0d820c6-7689-42e3-b8eb-1ac882b4235c.png)

And runs all examples instead of required one if:
* put the cursor on whitespace in the required line of the example table
![image](https://user-images.githubusercontent.com/72933/129974156-5717af8e-2875-40d3-ba61-c361d880f3de.png)

* press `run` gutter icon in the required examples table line
![image](https://user-images.githubusercontent.com/72933/129974237-f99163a9-a6eb-4abc-849d-9811c019fc72.png)

* place the cursor out of row `|....|` bounds in the example table
![image](https://user-images.githubusercontent.com/72933/129974414-2f84af3e-02cb-4bc2-8db5-89d4de786e5c.png)

**Comment by iromeo** [comment]
P.S: Not sure is it a bug in Cucumber+ plugin or in Gherkin language support plugin.

**Comment by maximehamm** [comment]
Hello Roman
I think it is now fixed ! Sorry for the delay !
Maxime
