### ISSUE TITLE
Russian letters displays as ### in the PDF

### ISSUE THREAD

**Issue by ilya-corp** [maximehamm/tzatziki#14]
When I export feature to PDF, Russian letters displays as symbols ####

**Comment by maximehamm** [comment]
Please, can you send me some russian feature to test that ?

**Comment by ilya-corp** [comment]
Hello!
In the attachment you can find an example of Russian feature file.
Regarding another problem, related to copying-pasting of table rows, I will try to reproduce again and born repro-steps. For now, it was a single fault, so I simply reported to you about that to avoid loosing of crash artefacts.
 
Thanks,
Ilya
  
>Воскресенье, 12 сентября 2021, 22:06 +03:00 от Maxime HAMM ***@***.***>:
> 
> 
>Please, can you send me some russian feature to test that ?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 
--
Ilya Scherbakov

**Comment by ilya-corp** [comment]
[Block User V4.zip](https://github.com/maximehamm/tzatziki/files/7170352/Block.User.V4.zip)

**Comment by maximehamm** [comment]
Hello

It will be fixed in next release !

I have replace the font to choose one which supports Cyrillic...
It will be also possible to add your custom font using a TTF : the file must be named "cucumber+.font.ttf" and stored in ".cucumber+" folder...

**Comment by maximehamm** [comment]
I will be pleased if you would mind add some review at IntelliJ IDEA market place :) 
Maxime
