### ISSUE TITLE
Enter key does not work in debugger or "Rename file" dialog if Cucumber+ 9 is enabled

### ISSUE THREAD

**Issue by ilya-corp** [maximehamm/tzatziki#17]
I have installed plugin Cucumber+ and have found that Enter key doesn't work when I add new variable to watch or when trying to rename class. I have disabled plugin and functionality was restored.
When I had enabled Cucumber+ again, working of Enter key was corrupted again.

My expectation is that Enter key must work as usually. Pressing Enter key must evaluate expression, pressing Enter must submit file renaming etc.
I use IntelliJ Community 2021.2.

**Comment by maximehamm** [comment]
It is fixed in next release
