### ISSUE TITLE
Unable to delete uncompleted row of table with examples

### ISSUE THREAD

**Issue by ilya-corp** [maximehamm/tzatziki#18]
I have following examples table in my scenario:

```
Протокол	Домен	Название отдела	Действие с переключателем отображения	Состояние отображения	Название региона	Локации	Язык
https://	ozon.ru	Отдел продаж	включает	включено	Часть Японии	Япония/Акита,Япония/Осака	Английский
https://	wildberries.ru	Отдел кадров	выключает	выключено	Алжирский	Алжир/Батна, Алжир/Бешар	Русский

```
When I added new line, but not complete it
```
  Примеры:                       
    | Протокол | Домен          |
    | https:// | ozon.ru        |
    | https:// | wildberries.ru |
    |          |                |
```

Since this moment I can't delete last line by selection+pressing Del or Backspace.
My expectation that selection+pressing Del or Backspace must remove line (maybe first press must delete content and second delete cells completely).

See screenshot.

**Comment by ilya-corp** [comment]
![can't delete row](https://user-images.githubusercontent.com/36953132/133440165-2b61bc3a-3b59-4353-a015-470e47687f2f.png)

**Comment by maximehamm** [comment]
Hello

There is a workaround : disable the plugin and fix the table (right click in editor and select "toggle Cucumber+)
Sorry its a bit tricky, I do not want to introduce regression to manage "broken tables"... 

...but I would like to investigate how you achieve to have such a last line in your table... can you please explain more how to do that ?
