### ISSUE TITLE
Toggle for table editing has no effect on shortcuts

### ISSUE THREAD

**Issue by theotherp** [maximehamm/tzatziki#20]
Pressing Ctrl+Shift+Cursor will always move columns or rows, no matter the state of the "Toggle Cucumber+" menu entry. I would've expected the shortcuts to be disabled as well. Not sure how easy to implement that is but I like to use Ctrl+Shift+Left/Right to select whole words.

In any case great plugin! Some of the functions do not work for us (Deprecation doesn't work with lambda step definitions) but the autocomplete is a great help!

**Comment by maximehamm** [comment]
Hello
- It is fixed !
- Nice to read that my plugin helps you 👍 Would you mind report this as a review at JetBrain Marketplace ?
- Can you give me an example about the "Deprecation doesn't work with lambda step definitions" ?
Maxime
