### ISSUE TITLE
Some dialogs require Ctrl+Enter to be pressed instead of Enter with the plugin installed

### ISSUE THREAD

**Issue by theotherp** [maximehamm/tzatziki#22]
Copy and paste a java class. In the dialog for the class name enter a new name and press the enter key. Nothing happens. You need to press Ctrl+Enter. With the plugin disabled pressing Enter is enough.
Same with the dialog to evaluate expressions.

**Comment by maximehamm** [comment]
Thank you for this feedback !
It will be fixed in next release !
