### ISSUE TITLE
Cucumber+ crashed during editing of glue file

### ISSUE THREAD

**Issue by ilya-corp** [maximehamm/tzatziki#23]
During editing of the glue file, Cucumber+ 9.0.3 crashed. See attachments.

**Comment by ilya-corp** [comment]
![Uploading screen.png…]()

**Comment by ilya-corp** [comment]
![screen](https://user-images.githubusercontent.com/36953132/135246616-acdd2f99-cab0-4a12-97e7-cfde4bc1fb20.png)

**Comment by ilya-corp** [comment]
[ServiceOnly.zip](https://github.com/maximehamm/tzatziki/files/7250829/ServiceOnly.zip)

**Comment by maximehamm** [comment]
Thank you for reporting.
It will be fixed from release 9.0.4
