### ISSUE TITLE
No "Export to PDF" when right click a file

### ISSUE THREAD

**Issue by johnnypenggg** [maximehamm/tzatziki#24]
Export to PDF is really nice function I want, but there is no "Export to PDF" when I right click a feature file, all other functions works fine, both on PyCharm and IDEA, I have no idea what happened, help!!!
I try o run the IDEA on JRE 11 & 12  because when i compile  the source code it says need JDK 11, however, it does not help.

**Comment by maximehamm** [comment]
Hello Jo !
Sorry I can't find any reason for that... please give me more feedback :
- does it still happen ? is it always the case or sometimes ?
- did you try by right click into the feature editor ? 
- did you try by right click from file name in the project tree window ?
- did you check the "File" or "Edit" menu when selecting a feature file in the project tree window ?
- is your file part of project resources  (i.e "src/test/resources" for example) ? is your project well configured for it ?
Thank you for your help
Maxime

**Comment by maximehamm** [comment]
I made some improvement... please let me know if it still occurs
