### ISSUE TITLE
Cannot export to PDF

### ISSUE THREAD

**Issue by ehupin** [maximehamm/tzatziki#33]
Hi!

I did not succeed to make the plugin works to export PDF. Here is the reproduction steps:

- running in PyCharm 2021.3.3 (build #PY-213.7172.26) on Ubuntu 20.04.3 LTS
- installed the Cucumber+ (version 11.1.7) and enabled it
- right-click on a "*.feature" file from the project tool window
- no "Export feature to PDF" option is shown in the context menu

Am I missing something?

Many thanks :)

**Comment by rayzistdev** [comment]
I am using WebStorm and getting the same issue.

**Comment by LeandreArseneault** [comment]
Try marking your repository as source root

**Comment by maximehamm** [comment]
Hello
Thank you Erick for reporting this.
Leandre is right : your .feature file should be part of project's resources...
Il will add a popup to explain this.
Kind regards
Maxime
