### ISSUE TITLE
When using IntelliJ 2021.2, when attempting to use Find/Replace on Feature Files Only, CTRL+V Fails to Function

### ISSUE THREAD

**Issue by nylifeinnj** [maximehamm/tzatziki#34]
It appears that when I tried to execute Find/Replace, if I attempt to Copy/Paste, nothing happens in the boxes, specifically when done on Feature Files.

**Comment by jimmylobo2** [comment]
I confirm this issue still occurs. I have to either copy the whole feature to an external editor to do some search and replace operation, or disable the Cucumber+ plugin in order to do the task in IntelliJ.

**Comment by maximehamm** [comment]
Hello Henry
I think it is now fixed with release 12.0.3. Can you please confirm ?
Maxime
