### ISSUE TITLE
Incompatible with IntelliJ 2022.2

### ISSUE THREAD

**Issue by postalservice14** [maximehamm/tzatziki#37]
The current version of the plugin on the marketplace is not compatible with IntelliJ 2022.2.

The exact error is "Incompatible: requires IDS build 221.* or earlier"

**Comment by JPKovacs** [comment]
I have the same issue. Can we expect soon to fix this issue? Thanks in advance!

**Comment by postalservice14** [comment]
Fixed with https://github.com/maximehamm/tzatziki/commit/b8d5fa5529dd7101b78f8c33e2cb5fc77a5f26b3
