### ISSUE TITLE
IntelliJ freezes when the plugin is installed 

### ISSUE THREAD

**Issue by uaru** [maximehamm/tzatziki#39]
rails application is running in the debug mode

The IntelliJ freezes for up to 5 minutes when the plugin is installed and HTTP Tool request causes the `ActionController::RoutingError (No route matches`. 
Disabling this plugin makes the problem disappear.

https://youtrack.jetbrains.com/issue/IDEA-303019/The-IDE-freezes-for-up-to-5-minutes-when-a-REST-method-with-erroneous-controller-name-is-run

**Comment by uaru** [comment]
Some stacktraces

[threadDumps-freeze-20221004-100254-IU-222.4167.29.zip](https://github.com/maximehamm/tzatziki/files/9711864/threadDumps-freeze-20221004-100254-IU-222.4167.29.zip)
[threadDumps-freeze-20221004-103303-IU-222.4167.29-213sec.zip](https://github.com/maximehamm/tzatziki/files/9711865/threadDumps-freeze-20221004-103303-IU-222.4167.29-213sec.zip)

**Comment by maximehamm** [comment]
Hello
This is fixed with release 12.0.3
Thank you
