### ISSUE TITLE
Plugins gherkin & org.intellij.intelliLang  required in MPS-2020.3.3

### ISSUE THREAD

**Issue by eteichm** [maximehamm/tzatziki#4]
Hello, I installed JetBrains MPS 2020.3.3 and added the Cucumber + plugin via Settings > Plugins.  This plugin required the installation of Gherkin.  I did it via web page https://plugins.jetbrains.com/plugin/9164-gherkin Gherkin required the installation of intelliLang and YAML (also via the plugins web page).  However for those plugins it did not find a plugin version compatible with MPS 2020.3.3. 
On MPS Slack I raised the issue and got the following feedback: These are all IDEA plugins, they won't help you much with MPS
If this is so, please indicate that Cucumber + plugin is not compatible with MPS.

**Comment by maximehamm** [comment]
Hello
Sorry for that. I confirm that I was not able to install Gherkin with MPS... You should report this to Jetbrain. 
You should consider using Intellij Community for example...
Kind regards 
Maxime

**Comment by eteichm** [comment]
Thanks.  I learned how to see with which tool and what version a plugin is compatible. Gherkin seems compatible with future versions of MPS. 
Best regards,
Eric
