### ISSUE TITLE
Feature Suggestion: Implement support for grouping test output under "Rule" tag

### ISSUE THREAD

**Issue by mrthehud** [maximehamm/tzatziki#40]
The optional "Rule" tag was added in Gherkin v6 - https://cucumber.io/docs/gherkin/reference/#rule

It would be nice if it was possible to group by Rule, between Feature and Scenario in the test output window.

**Comment by maximehamm** [comment]
Hello James
The test output is not managed by Cucumber+ plugin but by the Gherkin plugin (from Jetbrains)
I think what you think about already exists : 
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/4968224/223580300-defb23cf-6ec7-4e4e-b413-a45ff39ce8cd.png">

Maxime
