### ISSUE TITLE
I cannot paste any text into the search box after enabling the plugin.

### ISSUE THREAD

**Issue by yinssh1005** [maximehamm/tzatziki#44]
<img width="911" alt="image" src="https://user-images.githubusercontent.com/38479979/218459621-5df24411-9c75-4b86-a4f8-97baf948264d.png">

**Comment by maximehamm** [comment]
Hello Ethan 

This is fixed in release 12.0.3 (will ne available tomorrow)

If you are satisfied using cucumber+, please [share your experience](https://plugins.jetbrains.com/plugin/16289-cucumber-/reviews)

Maxime
