### ISSUE TITLE
Strange behaviour when pasting lines with IdeaVIM

### ISSUE THREAD

**Issue by cassm** [maximehamm/tzatziki#45]
Pycharm 2022.3.2, Cucumber+ 11.4.0, IdeaVIM 2.1.0

The issue I am having is that yanking and pasting a line results in fairly dramatic broken formatting.

e.g.:

```
| Thing 1 | Thing 2 | Thing 3 |
| 155     | Albert  | False   |
| 256     | Doris   | True    |
```

if I navigate to the second line of the table and hit `yy` then `p` (yank line then paste line), I get the following:

```
|  | Thing 1 | Thing 2 | Thing 3 |
|  | 155     | Albert  | False   |
|  | 155     | Albert  | False   |  | 256 | Doris | True |
|  |         |         |         |
```

What I would ideally expect to get would be, obviously:

```
| Thing 1 | Thing 2 | Thing 3 |
| 155     | Albert  | False   |
| 155     | Albert  | False   |
| 256     | Doris   | True    |
```

Is there a workaround for this? Should I just bind a hotkey for disabling the plugin when I want to paste something?

**Comment by maximehamm** [comment]
Hello Cass
Sorry, Cucumber+ does not support Vim
Yes it's a good idea : create a short cut to disable Cucumber+ when needed...
<img width="902" alt="image" src="https://user-images.githubusercontent.com/4968224/223574671-a9819ec8-cdec-4ab0-953b-645fcca1e852.png">

Maxime
