### ISSUE TITLE
Is there any possible to support deprecated displaying?

### ISSUE THREAD

**Issue by alaahong** [maximehamm/tzatziki#5]
Thanks for your working on such informative tool.

If you had the background of Java, you may know the IntelliJ will display the deprecated method with hyphen
![image](https://user-images.githubusercontent.com/3264250/118084145-c5fbc080-b3f2-11eb-9d68-f642ec88766d.png)

Do we have any possible to mark the deprecated step definitions as above way? Display in code promotion or feature is fine.

Background, there are multiple step definitions delivered with different version, we have to keep legacy steps for several version but need some ways to mention the deprecated status.

Thanks.

**Comment by maximehamm** [comment]
Hello Ian

Is this fine for you ? 



The color scheme will be up to you :



Would you please comment on https://plugins.jetbrains.com/plugin/16289-cucumber-/reviews? 
I would love to know which part of Cucumber + is most valuable to you :)

Kind regards,

Maxime

**Comment by alaahong** [comment]
Thanks for you quick response. Will comment on jetbrains later.

In feature is fine, at least user can know the status of used steps. 

One further request, do we have the possible to display in code promotion as below place too?
![image](https://user-images.githubusercontent.com/3264250/118447058-e98c7700-b722-11eb-9efe-2cea40ffe3fc.png)
![image](https://user-images.githubusercontent.com/3264250/118447232-1c366f80-b723-11eb-99ed-17abb1b548cf.png)

**Comment by maximehamm** [comment]
A will submit a new version 5.1.0 with the "display deprecated step" annotator... 
I will think about the second feature "display step method as code promotion"... I'm not sure it will be that easy...

**Comment by maximehamm** [comment]
I fact the "display step method as code promotion" already exists : it is named "Quick definition" and it is available from "View" menu : 

<img width="796" alt="image" src="https://user-images.githubusercontent.com/4968224/118458957-89cea580-b6fb-11eb-88ac-9b781bb0c2fd.png">

**Comment by alaahong** [comment]
> I fact the "display step method as code promotion" already exists : it is named "Quick definition" and it is available from "View" menu :
> 
> <img alt="image" width="796" src="https://user-images.githubusercontent.com/4968224/118458957-89cea580-b6fb-11eb-88ac-9b781bb0c2fd.png">

Yes，it's a kind of promotion. But as expect, just like the first screenshot, the IntelliJ IDEA can show the deprecated Java method while user typing.
Otherwise, while users type in feature, they don't know the deprecated status before step selected as below, there are two methods one is alive, another is deprecated.
![image](https://user-images.githubusercontent.com/3264250/118462400-38d9a400-b731-11eb-81cf-a7518ba469ce.png)
![image](https://user-images.githubusercontent.com/3264250/118462466-48f18380-b731-11eb-812c-88c920560ba2.png)

It doesn't matter if met tech bottleneck on the implementation. It already looks better in feature than previous. 
Thanks!

**Comment by maximehamm** [comment]
I took a look: I could hack the thing but it would be really naughty. You have to ask for the evolution of the Gherkin plug-in... at the "CucumberCompletionContributor" class level

**Comment by alaahong** [comment]
Just try toto work with new version including this function, seems not work yet. Is that based by https://youtrack.jetbrains.com/issue/IDEA-269898 ?
![image](https://user-images.githubusercontent.com/3264250/119294477-20184380-bc87-11eb-8d43-04e19348fbdf.png)

**Comment by maximehamm** [comment]
I added a new feature that generated a regression... sorry for that. It will be fixed in next release 5.2.1 of Cucumber+
(The issue you mention is indeed the reason for this regression. The new feature (5.2.0) consists in allowing to navigate to the latest known implementation of a feature even when changing the wording of this feature in Gerkin file)
The 5.2.1 release should be available in few hours or tomorrow.

**Comment by alaahong** [comment]
The 5.2.1 is fine now, thanks!

**Comment by maximehamm** [comment]
Hi Ian

Please write some feedback about what is the best Cucumber+ feature at Intellij Marketplace ;)

**Comment by maximehamm** [comment]
Hello
FYI : The next version will allow better completion! And it will display deprecated steps in a crossed out way !
I'm working also on "code promotion" as you were requested... but not sure it is allowed !

<img width="632" alt="image" src="https://user-images.githubusercontent.com/4968224/123429449-43f0e100-d5c7-11eb-9d57-50d22516d9f9.png">

**Comment by maximehamm** [comment]
Code promotion is available also !
Let's press "ALT-Space" when the completion popup is available : 
![image](https://user-images.githubusercontent.com/4968224/123433034-5240fc00-d5cb-11eb-99b9-ffa77cc58650.png)
