### ISSUE TITLE
Kotlin step definitions not detected

### ISSUE THREAD

**Issue by Luxor** [maximehamm/tzatziki#54]
E.g

```
init {
        Then("A step '{word}'") { number: String ->
            val currentCallList = getCurrentCallList()

````

**Comment by maximehamm** [comment]
Hello
Step are detected by "Gherkin" plugin which is a JetBrains plugin... may be you can look forward Jetbrain.
PS : I see that you try to put step definition inside constructor ? Is that relevant ?
Maxime
