### ISSUE TITLE
Support for language specific auto completion

### ISSUE THREAD

**Issue by eitzenbe** [maximehamm/tzatziki#56]
Hi Maxime, 

I was wondering if there is any chance that such a feature could be added ?

So like when i have

@When("I do somethjing")
@Wenn("Ich etwas tue")
public void ....

@Then("I somethjing happens")
public void ....

and I am in an english feature file when I enter "When I" then the autocompletion shows TWO options
but when I am in a german feature file and I enter "Wenn I" i would only get the single german step def proposed?

Would be interested to see this being supported ;)

**Comment by maximehamm** [comment]
Hello 
I'm not sure this will fit for all Cucumber+ user... then here is what I've done : 
--> Let filter completion according to tag filtering setup

<img width="962" alt="image" src="https://github.com/maximehamm/tzatziki/assets/4968224/539666c6-82b3-40f2-931d-d1d34c9d95e7">

This will be available in release 16.5

Please rate the plugin if you like it :)
