### ISSUE TITLE
PyCharm CE & pytest-bdd issues

### ISSUE THREAD

**Issue by vlad230** [maximehamm/tzatziki#57]
I am currently using the latest PyCharm community on my Mac (for Python & pytest-bdd testing) and it seems something is not working as it should. 
For example: I cannot run a feature file from the IDE, cannot cmd + click on steps to go to the step definition, cannot see step suggestions etc. 
What am I doing wrong?

**Comment by maximehamm** [comment]
Hello
Cucumber+ supports only Java, Kotlin, and a little bit Scala.
Sorry for that !
