### ISSUE TITLE
Improvement suggestion: Link to GitHub Issues instead of LinkeIn profile to report errors

### ISSUE THREAD

**Issue by s2k** [maximehamm/tzatziki#59]
Hi,

Reporting bugs would more convenient if the link shown in the IDE (RubyMine in this case) pointed to the GitHub issues page, instead of the LinkedIn profile. Is it possible to change this link to point to https://github.com/maximehamm/tzatziki/issues?

<img width="816" alt="Screenshot 2023-12-03 at 10 27 16" src="https://github.com/maximehamm/tzatziki/assets/118248/576af385-a755-47e3-bc80-f0da2c15f282">

Searching in the repo, I found the particular link in only one place:

```zsh
tzatziki ᚠ master > find . -type f -exec grep -Hin "https://www.linkedin.com/in/maxime-hamm/" {} \;
./plugin/src/main/resources/META-INF/plugin.xml:20:            url="https://www.linkedin.com/in/maxime-hamm/">Maxime HAMM</vendor>
```

**Comment by maximehamm** [comment]
Done.
Thank you for the suggestion
