### ISSUE TITLE
Is there any way could disable new function of v5.2 ?

### ISSUE THREAD

**Issue by kaola89** [maximehamm/tzatziki#6]
Hi Maxime HAMM,

 This plugin is good for me, thanks for contribution.

I want use the version v5.1 function, display the deprecated step with highlight.
But for the new function  of v5.2, I want disable it, is there any way control this ?

And is there any plan to support highlight steps when  deprecated entire class?
Like this in IntelliJ.
![image](https://user-images.githubusercontent.com/36156723/119966955-6995c500-bfde-11eb-9089-50b9a45968c5.png)

Thanks.

**Comment by maximehamm** [comment]
Hello Mr / Mrs Koala89 !

I will plan to support deprecated class as soon as possible... and I will find a way to let you disable this !

I would be happy if you could rate cucumber+ at Intellij Market place ! Tell us why Cucumer+ is good for you ?

Kind regards,

Maxime

**Comment by kaola89** [comment]
Thanks for your support, I will recommend Cucumber+ into our team.
