### ISSUE TITLE
Incompatible with Intellj 233.*

### ISSUE THREAD

**Issue by Mengna2009** [maximehamm/tzatziki#61]
recently upgraded Intellj to 233.*, but Cucumber version 15.3.3, received above note

**Comment by s2k** [comment]
This seems to duplicate https://github.com/maximehamm/tzatziki/issues/60.

**Comment by maximehamm** [comment]
Hello
A new version of Cucumber+ will be available in two business days (i.e after been reviews by Jetbrain team)
Please try again then :)
Maxime
