### ISSUE TITLE
Plugin doesn't recognize definitions from jars in the classpath

### ISSUE THREAD

**Issue by clabautdidier** [maximehamm/tzatziki#62]
We have some commonly used definitions in a separate project, and want to use them in our QA projects.

Unfortunately the IntelliJ plugin doesn't find these definitions unless we also add the definition library project itself as a module to the project. Simply having it on the classpath through Gradle dependencies is not enough.

**Comment by maximehamm** [comment]
Hello
I'm not sure this is possible... are you able to run the test with this configuration ??
May one possible thing for Cucumber+ is to display those Gherkin file in its features view...
Please give me some feedback 
Maxime

**Comment by maximehamm** [comment]
Adding a new button to let display Gherkin file not part from sources/resources path... is it good enough for you ?

<img width="398" alt="image" src="https://github.com/maximehamm/tzatziki/assets/4968224/e43a4237-71a6-4ac3-9b1b-a1945ad47d6b">
