### ISSUE TITLE
Execute scenario buttons not displayed in 15.4

### ISSUE THREAD

**Issue by riverty-chathuranga** [maximehamm/tzatziki#63]
With the new version 15.4, the execute/play button (green play button) is not displayed near the scenario keyword and feature keyword. This happens with JetBrains Rider IDE latest version.

**Comment by maximehamm** [comment]
Hello Riverty
The green play icon not managed by Cucumber+ but is managed by the plugin dedicated by the language you're using (like Cucumber for Java, Cucumber for Scala, etc)...
