### ISSUE TITLE
random order of feature files

### ISSUE THREAD

**Issue by Vladek721** [maximehamm/tzatziki#64]
The feature files in my project ordered in a specific way. Why is this plugin doesn't display them in the same order? Also, how is this plugin actually ordering them in the feature files view? By tags it works correctly, it orders all my scenarios in alphabetical way all the tags. But once I switch to "group by modules" - it looks weird. I don't see the any connection there ... 

This is how it looks in my project:
<img width="217" alt="image" src="https://github.com/maximehamm/tzatziki/assets/62042923/bf01e6c7-61c7-4086-be55-2a589a3d3fe9">

And this is in plugin tab:
<img width="284" alt="image" src="https://github.com/maximehamm/tzatziki/assets/62042923/048d28d5-86a3-48d2-99e5-73754ddb6883">

**Comment by maximehamm** [comment]
Hello Vladek721
No reason not to order them :)
It will be available in next release.
Thanks for that
Please note & review my plugin !

**Comment by Vladek721** [comment]
Thank you so much @maximehamm Can't wait for the next release already :)
