### ISSUE TITLE
Unable to add breakpoint in feature file

### ISSUE THREAD

**Issue by SachinKumar768** [maximehamm/tzatziki#67]
Hello,
I am using this plugin for my Gherkhin feature files with python scripts. I can able to add a breakpoint in the python script but unable add a breakpoint in the feature file. I am afraid that did I miss any settings or it is supported that way? Please guide me.

**Comment by maximehamm** [comment]
Hello
Cucumber+ will display breakpoint in Gherkin files according to step definition. 
This was tested for Java, Kotlin, Scala...
Anyway Cucumber+ will only display breakpoint in the margin, but it can not add new breakpoint from Gherkin file...
