### ISSUE TITLE
Gherkin auto-complete?

### ISSUE THREAD

**Issue by LimeBlast** [maximehamm/tzatziki#7]
Hi, I love this plugin, thank you so much for creating and continuing to support it.

Can I make a request? Do you have any plans to include autocomplete for feature files? i.e. the ability to start typing a step definition within a .feature file, and have it automatically suggest other steps which already exist?

I've noticed a few other IDEs have plugins which provide this (eg: https://github.com/austincrft/sublime-gherkin-auto-complete-plus), and it would be really cool if JetBrains IDEs did too.

Thank you.

**Comment by LimeBlast** [comment]
Some minor updates, now I've played with Cucumber+ a little more.

It seems like there is some amount of autocomplete available, but this seems to be based on steps defined within the `step_definitions` folder.

What I'm more interested in is having it read other `.feature` files, and use than to populate an autocomplete. I would find this much more useful, as I'm often not going to have access to defined steps, especially early in a project.

I think I've also found a bug, which is causing the autocomplete to look at step definitions within bundled gems.

eg:

- http://share.foxsoft.co.uk/h3CaFO
- http://share.foxsoft.co.uk/OZ6Lcy

Thank you

**Comment by maximehamm** [comment]
Hello Daniel

About the bug : I assume you're using Ruby and it's [IntelliJ plugin](https://plugins.jetbrains.com/plugin/1293-ruby)... the screencast shows that the navigation is not going to the wright location... this feature is provided by Ruby's plugin, not by Cucumber+. Please report this [here](https://youtrack.jetbrains.com/issues/RUBY)

About the expected feature : I understand that you except step completion to suggest all available steps in Gherkin files, not only those having an implentation... This completion is manage bu the [Gherkin plugin](https://plugins.jetbrains.com/plugin/9164-gherkin). But here I think Cucumber+ can do something for you :) I will investigate more and let you know !

**Comment by LimeBlast** [comment]
Hi, thank you for the info. I'll report the bug accordingly :)

As for feature-based autocompletion, if you could add that, that would be amazing 🥇 

Thank you.

**Comment by maximehamm** [comment]
Hi
Here is how I propose to manage it :
<img width="568" alt="image" src="https://user-images.githubusercontent.com/4968224/123405207-e13d1c80-d5a9-11eb-8a52-55df94424c71.png">

- The icon tells you if the completion comes from a feature implementation or a feature
- The right side gives you the name of the file where the proposal step comes from (i.e a Java, Ruby, Kotlin, etc) or a feature name. You will also know in how many files the step is used, for exemple : toto.feature (+2) )

Is that good enough ?

I will also plan to do that :
-  Strike out completion step linked to a deprecated implementation (but I'm not sure this will work for Ruby... It will work for Java, Kotlin and Javascript)
- Showing a preview of the scenario near the completion proposal

Maxime

**Comment by LimeBlast** [comment]
That's amazing! Yes, that looks perfect. Thank you.

**Comment by maximehamm** [comment]
Cucumber+ version 8.0.0 si submitted... it should be available this afternoon or maybe next monday !
Please report at [Jetbrain's plugin market](https://plugins.jetbrains.com/plugin/16289-cucumber-) place how much you like Cucumber+ 😊

**Comment by LimeBlast** [comment]
Yes of course, this is amazing. Thank you.

I'm off work next week, so I won't get to test it until the week after, but I eagerly look forward to it.
