### ISSUE TITLE
Cannot select different context root

### ISSUE THREAD

**Issue by biscuit314** [maximehamm/tzatziki#71]
I have a library which we develop in multiple programming languages.  Our feature files are written to describe the behaviour of the library, and applies to each language.  Therefore the folder our feature files live in are not in the same folder structure as any one language's project.

In the IDE we handle this by creating a second context root - the first is for the code/project the second is for the feature files.  When we use Cucumber+ it does not find any feature files because it appears only to l look in the code/project context root.

Is there a way to change where Cucumber+ finds feature files?

**Comment by biscuit314** [comment]
Okay, maybe it is not a matter of multiple context roots.  I opened a new project directly at the root of the feature files (i.e. whose subfolders contain feature files) and it did not detect feature files therein.  Then I tried again opening a new project in a folder that directly contains feature files and again Cucumber+ did not detect any feature files.

It is quite likely there is an issue with my setup.  I have opened a ticket with JetBrains to guide me (first time I've tried this with a multi-language/single-features approach).  I'll provide more details as I get them.

**Comment by maximehamm** [comment]
Hello Michael
The "Run" icon new the feature is not managed by "cucumber+" (the plugin adds icons near scenario outline tables lines only)
The "Run" icon is managed by the plugin dedicated to the language you're using... for example "Cucumber for Java"...
