### ISSUE TITLE
Cannot generate PDF: "Common parent path "features" should be part of same ressource path..."

### ISSUE THREAD

**Issue by biscuit314** [maximehamm/tzatziki#72]
This error occurs when I try to generate a PDF:

"Common parent path "features" should be part of the same ressource path..."   

Unfortunately that is all I can see in the error notification bubble (note "resource" is spelled "ressource" in the error message - that's not a typo on my part here).

To ensure the problem was not due to my project's complex folder structure structure I created a clean folder and copied my feature files there.  Then I opened that folder as a new project with WebStorm.  The same error occurred.  No folder named `.cucumber+` was created.

This is happening in both Windows and Linux.

What do I do to adjust which paths or configs to get this to work?

**Comment by maximehamm** [comment]
Hello Michael
Gherkin file have to be part of resource path... is it the case ? 
Does the folder icon look like this :
<img width="110" alt="image" src="https://github.com/maximehamm/tzatziki/assets/4968224/10aab771-4e52-4ef2-93b4-d43dcad61261">

**Comment by biscuit314** [comment]
What is a resource path?  Do you mean the feature files (Gherkin files) have to be in a folder named "resources"?  Mine are in a folder named "features"  Cucumber+ has detected them all, but I get the following when I try to generate PDF:
![ressource](https://github.com/maximehamm/tzatziki/assets/8892155/bfaaa550-363d-427c-a65e-382575f8115a)

In the above, my feature files were in a different location, but I've tried copying them into all manner of path structures, each with the same result.  I tried moving the features file into the project, renaming it to `resources` to `ressource`, to `resource`  Each time Cucumber+ finds all of my feature files, lets me filter by tags, etc.  But whenever I click the PDF button I get some variation of the message above.

**Comment by biscuit314** [comment]
I found the problem.  I had to mark the folder as Test Sources Root:
![test-root](https://github.com/maximehamm/tzatziki/assets/8892155/1acb25e8-acf9-45c8-9c2b-b5744349720e)

**Comment by maximehamm** [comment]
Well done !
