### ISSUE TITLE
Issue when using '*' as step keyword

### ISSUE THREAD

**Issue by Dantekotta** [maximehamm/tzatziki#77]
Hi! I noticed that, I believe, after Intellij update, i cannot create step definition methods from .feature file when starting with "*".
When I try to do it, it just opens chosen step definition file. When creating new one, it is empty.
I noticed some IDE errors, Exception i plugin Cucumber + (17.2.2)
First errors created while clicking "create step definition" option from context action, and next ones when I choose file.

[Stacktrace-afterclickinCreateStepDefs.txt](https://github.com/maximehamm/tzatziki/files/15134134/Stacktrace-afterclickinCreateStepDefs.txt)
[Stacktrace-afterChoosingFile.txt](https://github.com/maximehamm/tzatziki/files/15134135/Stacktrace-afterChoosingFile.txt)

In second one there is clearly said:

> Caused by: java.lang.AssertionError: Unexpected token: '*'

I have Cucumber for Java 241.14494.158 plugin and Gherkin 241.14494.150 plugin if that matters.

Sorry if I missed something, it's first time I'm creating an issue. If I should share some more info, let me know what could be helpful.

**Comment by maximehamm** [comment]
Hi 
Thank you for reporting this.
It is fixed. Wait for next release on Monday or Tuesday
Maxime
