### ISSUE TITLE
there are several requirements in the use process

### ISSUE THREAD

**Issue by ychengke** [maximehamm/tzatziki#8]
Very good plug-in, there are several requirements in the use process:
1. If an external file is imported in the feature, click the file name to open the corresponding file, which is convenient for us to view.
2. The formatting of Chinese seems to be incorrect all the time.

**Comment by maximehamm** [comment]
Hi
1. Sorry, can you be more specific for this first point ? What do you mean about "importing in the feature" ? What behavior do u expect ?
2. Are you talking about the feature editor ? Or about exporting to PDF ?
Can you please send me a chinese sample to test this ?
Maxime

**Comment by maximehamm** [comment]
Hello
Can you please give me some feedback ?
Thank you !
