### ISSUE TITLE
Gutters rendering issue

### ISSUE THREAD

**Issue by iromeo** [maximehamm/tzatziki#9]
MacOS 11.3, IDEA-UE 2021.2, cucumber+ 9.0.0

Step definition files are very inconvenient to read/edit/check vcs diff due to: 
![image](https://user-images.githubusercontent.com/72933/129896246-ede3404c-6b11-460e-9f47-7dae0d63aea1.png)

More over I cannot disable gutters because I cannot find them in `Settings|Editor|General|Gutter Icons` settings panel
```
IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Licensed to JetBrains Team / Roman Chernyatchik
You have a perpetual fallback license for this version.
Subscription is active until March 30, 2023.
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2448M
Cores: 16
Registry: analyze.exceptions.on.the.fly=true, ide.windowSystem.autoShowProcessPopup=true, idea.profiler.jvm.dtrace=true
Non-Bundled Plugins: IdeaVIM (0.69), org.jetbrains.idea.grammar (2021.1.1), Jetbrains TeamCity Plugin (2021.1.98828), Pythonid (212.4746.96), io.nimbly.tzatziki (9.0.0)
Kotlin: 212-1.5.10-release-IJ4746.92
```

**Comment by maximehamm** [comment]
Hello Roman 

Thanks for your feedback !

Please retry using v.9.0.1 witch will be available tomorrow ! Please report me if it is fixed or not !

Maxime

**Comment by iromeo** [comment]
I've installed `9.0.2` gutters are ok now. Thank you for the fast feedback and fix!
![image](https://user-images.githubusercontent.com/72933/129971298-39d42c4b-fc87-4708-b837-1714fd38a977.png)

P.S:  Cucumber+ gutters still missing in configure gutter icons dialog. I don't want to turn them off, but seems IDEA assumes that uses could turn off gutters that they don't need
![image](https://user-images.githubusercontent.com/72933/129971432-f6f09d73-d0ff-4bd0-88d1-6471fcb16653.png)

**Comment by maximehamm** [comment]
I will plan to let turn of Cucumber+ gutter icons !
If possible, please, add some review at Intellij Markeplace ;)
Maxime
